### PR TITLE
All tests: minor refactorings to simplify upstream modifications and testing

### LINKED ISSUE #19: Modify variables to enable simpler upstream refactorings
Many objects in the Tests refer very explicitly to types and names used in upstream code.

However, in light of the refactorings that will be needed to implement, e.g.: 
- https://github.com/BHoM/BHoM/issues/1590
- https://github.com/BHoM/BHoM_Engine/issues/3263
- https://github.com/BHoM/BHoM/issues/1591

it is desirable to use newer C# features such as `new()` (without repeating/expliciting the type where it is implicit) and `var` to make the job easier and reduce the noise from irrelevant renamings.

### LINKED ISSUE #20: Tests to inherit from `BH.oM.Test.NUnit.NUnitTest` to ensure dynamic load and binding of dependencies
All tests should inherit from `BH.oM.Test.NUnit.NUnitTest` to ensure the dynamic load and binding of dependencies.

### PR DESCRIPTION
**Pull request by alelom**
Closes https://github.com/BHoM/DiffingTests_Prototypes/issues/19
Closes https://github.com/BHoM/DiffingTests_Prototypes/issues/20

This PR does some minor changes to facilitate testing when dealing with Upstream modifications, such as the ones required for https://github.com/BHoM/BHoM_Engine/pull/3268 and others (see #19). It also adds a few tests for https://github.com/BHoM/BHoM_Engine/pull/3268.

The logic of previously existing tests is not affected by these changes.

### CODE REVIEW

**Comment by alelom** [comment]
Profiling results, running the `DiffingProfiling` project:
- Before (all on `develop`):  
2024-01-29 20_45_06-C__Users_alombardi_Documents_GitHub_DiffingTests_Prototypes_DiffingProfiling_bin
- When on https://github.com/BHoM/BHoM_Engine/pull/3268:  
2024-01-29 20_24_42-Select C__Users_alombardi_Documents_GitHub_DiffingTests_Prototypes_DiffingProfil

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed by @pawelbaran when testing the linked PR so this is good to merge following conversation with @alelom

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 21231289147

**Pull request merged**
